layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 10
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name
      - old-pelican-blog

social_media:
#  behance: paulmendes
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: paulse_performance
  # keybase: your_username
  linkedin: paul-mendes
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 9593658
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

#topics:
#  - name: CSS
#    web_url: https://github.com/topics/css
#    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
#
#  - name: Flask
#    web_url: https://github.com/topics/flask
#    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/flask/flask.png
#
#  - name: Sass
#    web_url: https://github.com/topics/sass
#    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

#skills:
#     category: Web Design
#       - name: HTML
#         web_url: https://github.com/topics/css
#         image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
#
#       - name: Flask
#         web_url: https://github.com/topics/css
#         image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
#
#     - Back End:
#       - name: Python
#
#       - name: Sass
#         web_url: https://github.com/topics/sass
#         image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

skills:
 - category: Webdesign
   tools:
    - name: HTML
      web_url: https://github.com/topics/css
      image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

    - name: CSS
      web_url: https://github.com/topics/css
      image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

    - name: CSS
      web_url: https://github.com/topics/css
      image_url: assets/img/jekyll.png

 - category: Server Side
   tools:
    - name: Flask
      web_url: https://github.com/topics/flask
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/flask/flask.png

    - name: Python
      web_url: https://github.com/topics/sass
      image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
